PARAMS = [
  ['single backslash', '\\', ['\\']],
  ['alphabets', 'abcdef', 'abcdef'.chars.to_a],
  ['numbers', '445454', ['445454']],
  ['backslash after number', '123\\', ['123', '\\']],
  ['double backslash after number', '123\\\\', ['123', '\\\\']],
  ['decimal', '12.56', ['12.56']],
  ['incomplete decimal', '12.\\', ['12', '.', '\\']],
  ['numbers and alphabets', '5x', '5x'.chars.to_a],
  ['decimals and alphabets', '5.8x', ['5.8', 'x']],
  ['string with spaces', '3 x', %w[3 x]],
  ['operators', '+-*/=()[]_^{}', '+-*/=()[]_^{}'.chars.to_a],
  [
    'numbers, alphabets and operators',
    '3 + 5x - 5y = 7',
    ['3', '+', '5', 'x', '-', '5', 'y', '=', '7']
  ],
  ['symbols', '\\alpha\\beta', ['\\alpha', '\\beta']],
  ['symbols appended with number', '\\frac2x', ['\\frac', '2', 'x']],
  ['null delimiter #1', '\\left\\{\\right.', ['\\left', '\\{', '\\right', '.']],
  [
    'matrix',
    '\\begin{matrix}a & b \\\\ c & d \\end{matrix}',
    ['\\begin{matrix}', 'a', '&', 'b', '\\\\', 'c', '&', 'd', '\\end{matrix}']
  ],
  [
    'matrix with alignment',
    '\\begin{matrix*}[r]a & b \\\\ c & d \\end{matrix*}',
    [
      '\\begin{matrix*}',
      '[',
      'r',
      ']',
      'a',
      '&',
      'b',
      '\\\\',
      'c',
      '&',
      'd',
      '\\end{matrix*}'
    ]
  ],
  [
    'matrix with negative sign',
    '\\begin{matrix}-a & b \\\\ c & d \\end{matrix}',
    ['\\begin{matrix}', '-', 'a', '&', 'b', '\\\\', 'c', '&', 'd', '\\end{matrix}']
  ],
  [
    'simple array',
    '\\begin{array}{cc} 1 & 2 \\\\ 3 & 4 \\end{array}',
    [
      '\\begin{array}',
      '{',
      'c',
      'c',
      '}',
      '1',
      '&',
      '2',
      '\\\\',
      '3',
      '&',
      '4',
      '\\end{array}'
    ]
  ],
  ['subscript', 'a_{2,n}', ['a', '_', '{', '2', ',', 'n', '}']],
  [
    'superscript with curly braces',
    'a^{i+1}_3',
    ['a', '^', '{', 'i', '+', '1', '}', '_', '3']
  ],
  [
    'issue #33',
    ''"\\begin{bmatrix}
  a_{1,1} & a_{1,2} & \\cdots & a_{1,n} \\\\
  a_{2,1} & a_{2,2} & \\cdots & a_{2,n} \\\\
  \\vdots  & \\vdots  & \\ddots & \\vdots  \\\\
  a_{m,1} & a_{m,2} & \\cdots & a_{m,n}
  \\end{bmatrix}"'',
    [
      '\\begin{bmatrix}',
      'a',
      '_',
      '{',
      '1',
      ',',
      '1',
      '}',
      '&',
      'a',
      '_',
      '{',
      '1',
      ',',
      '2',
      '}',
      '&',
      '\\cdots',
      '&',
      'a',
      '_',
      '{',
      '1',
      ',',
      'n',
      '}',
      '\\\\',
      'a',
      '_',
      '{',
      '2',
      ',',
      '1',
      '}',
      '&',
      'a',
      '_',
      '{',
      '2',
      ',',
      '2',
      '}',
      '&',
      '\\cdots',
      '&',
      'a',
      '_',
      '{',
      '2',
      ',',
      'n',
      '}',
      '\\\\',
      '\\vdots',
      '&',
      '\\vdots',
      '&',
      '\\ddots',
      '&',
      '\\vdots',
      '\\\\',
      'a',
      '_',
      '{',
      'm',
      ',',
      '1',
      '}',
      '&',
      'a',
      '_',
      '{',
      'm',
      ',',
      '2',
      '}',
      '&',
      '\\cdots',
      '&',
      'a',
      '_',
      '{',
      'm',
      ',',
      'n',
      '}',
      '\\end{bmatrix}'
    ]
  ],
  ['issue #51', '\\mathbb{R}', ['&#x0211D;']],
  [
    'issue #55',
    '\\begin{array}{rcl}ABC&=&a\\\\A&=&abc\\end{array}',
    [
      '\\begin{array}',
      '{',
      'r',
      'c',
      'l',
      '}',
      'A',
      'B',
      'C',
      '&',
      '=',
      '&',
      'a',
      '\\\\',
      'A',
      '&',
      '=',
      '&',
      'a',
      'b',
      'c',
      '\\end{array}'
    ]
  ],
  ['issue #60', '\\mathrm{...}', ['\\mathrm', '{', '.', '.', '.', '}']],
  [
    'issue #61',
    '\\frac{x + 4}{x + \\frac{123 \\left(\\sqrt{x} + 5\\right)}{x + 4} - 8}',
    [
      '\\frac',
      '{',
      'x',
      '+',
      '4',
      '}',
      '{',
      'x',
      '+',
      '\\frac',
      '{',
      '123',
      '\\left',
      '(',
      '\\sqrt',
      '{',
      'x',
      '}',
      '+',
      '5',
      '\\right',
      ')',
      '}',
      '{',
      'x',
      '+',
      '4',
      '}',
      '-',
      '8',
      '}'
    ]
  ],
  [
    'issue #63',
    '\\sqrt {\\sqrt {\\left( x^{3}\\right) + v}}',
    [
      '\\sqrt',
      '{',
      '\\sqrt',
      '{',
      '\\left',
      '(',
      'x',
      '^',
      '{',
      '3',
      '}',
      '\\right',
      ')',
      '+',
      'v',
      '}',
      '}'
    ]
  ],
  [
    'issue #77',
    '\\left[\\begin{matrix}1 & 0 & 0 & 0\\\\0 & 1 & 0 & 0\\\\0 & 0 & 1 & 0\\\\0 & 0 & 0 & 1\\end{matrix}\\right]',
    [
      '\\left',
      '[',
      '\\begin{matrix}',
      '1',
      '&',
      '0',
      '&',
      '0',
      '&',
      '0',
      '\\\\',
      '0',
      '&',
      '1',
      '&',
      '0',
      '&',
      '0',
      '\\\\',
      '0',
      '&',
      '0',
      '&',
      '1',
      '&',
      '0',
      '\\\\',
      '0',
      '&',
      '0',
      '&',
      '0',
      '&',
      '1',
      '\\end{matrix}',
      '\\right',
      ']'
    ]
  ],
  [
    'issue #78',
    'x^{x^{x^{x}}} '\
    '\\left(x^{x^{x}} \\left(x^{x} \\left(\\log{\\left(x \\right)} + 1\\right) \\log{\\left(x \\right)} + '\
    '\\frac{x^{x}}{x}\\right) \\log{\\left(x \\right)} + \\frac{x^{x^{x}}}{x}\\right)',
    [
      'x',
      '^',
      '{',
      'x',
      '^',
      '{',
      'x',
      '^',
      '{',
      'x',
      '}',
      '}',
      '}',
      '\\left',
      '(',
      'x',
      '^',
      '{',
      'x',
      '^',
      '{',
      'x',
      '}',
      '}',
      '\\left',
      '(',
      'x',
      '^',
      '{',
      'x',
      '}',
      '\\left',
      '(',
      '\\log',
      '{',
      '\\left',
      '(',
      'x',
      '\\right',
      ')',
      '}',
      '+',
      '1',
      '\\right',
      ')',
      '\\log',
      '{',
      '\\left',
      '(',
      'x',
      '\\right',
      ')',
      '}',
      '+',
      '\\frac',
      '{',
      'x',
      '^',
      '{',
      'x',
      '}',
      '}',
      '{',
      'x',
      '}',
      '\\right',
      ')',
      '\\log',
      '{',
      '\\left',
      '(',
      'x',
      '\\right',
      ')',
      '}',
      '+',
      '\\frac',
      '{',
      'x',
      '^',
      '{',
      'x',
      '^',
      '{',
      'x',
      '}',
      '}',
      '}',
      '{',
      'x',
      '}',
      '\\right',
      ')'
    ]
  ],
  [
    'max',
    '\\max_{x \\in \\[a,b\\]}f(x)',
    [
      '\\max',
      '_',
      '{',
      'x',
      '\\in',
      '\\[',
      'a',
      ',',
      'b',
      '\\]',
      '}',
      'f',
      '(',
      'x',
      ')'
    ]
  ],
  [
    'multi-line #4',
    "c_l = {L' \\over {1\\over2} \\rho_\\textrm{ref} q_\\textrm{ref}^2 c_\\textrm{ref}} \\qquad
    c_d = {D' \\over {1\\over2} \\rho_\\textrm{ref} q_\\textrm{ref}^2 c_\\textrm{ref}} \\qquad
    \\vec{c}_m = {\\vec{M}' \\over {1\\over2} \\rho_\\textrm{ref} q_\\textrm{ref}^2 c_\\textrm{ref}^2},",
    [
      'c', '_', 'l', '=',
      '{',
      'L', "'",
      '\\over',
      '{', '1', '\\over', '2', '}',
      '\\rho', '_', '\\textrm{ref}', 'q', '_', '\\textrm{ref}', '^', '2', 'c', '_', '\\textrm{ref}', '}',
      '\\qquad',

      'c', '_', 'd', '=',
      '{', 'D', "'",
      '\\over',
      '{', '1', '\\over', '2', '}',
      '\\rho', '_', '\\textrm{ref}', 'q', '_', '\\textrm{ref}', '^', '2', 'c', '_', '\\textrm{ref}', '}',
      '\\qquad',

      '\\vec', '{', 'c', '}', '_', 'm', '=',
      '{', '\\vec', '{', 'M', '}', "'",
      '\\over',
      '{', '1', '\\over', '2', '}',
      '\\rho', '_', '\\textrm{ref}', 'q', '_', '\\textrm{ref}', '^', '2', 'c', '_', '\\textrm{ref}', '^', '2', '}', ','
    ]
  ]
].freeze

RSpec.describe Latexmath do
  it 'has a version number' do
    expect(Latexmath::VERSION).not_to be nil
  end

  PARAMS.each do |param|
    it (param[0]).to_s do
      expect(Latexmath::Tokenizer.new(param[1]).tokenize).to eq(param[2])
    end
  end
end
